services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run python manage.py
    volumes:
      - ./migrations/:/home/python_user/migrations
      - ./scripts:/home/python_user/scripts
      - ./src:/home/python_user/src
    ports:
      - 8100:8100
    env_file:
      - ./.env
    depends_on:
      - db
    links:
      - "db:${POSTGRES_SQLALCHEMY__HOST?Variable not set}"
  db:
    image: postgres:18.1-alpine3.23
    container_name: postgres
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_SQLALCHEMY__USERNAME} -d ${POSTGRES_SQLALCHEMY__DATABASE}",
        ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/dataa
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/dataa
      - POSTGRES_PASSWORD=${POSTGRES_SQLALCHEMY__PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_SQLALCHEMY__USERNAME?Variable not set}
      - POSTGRES_DB=${POSTGRES_SQLALCHEMY__DATABASE?Variable not set}
    ports:
      - "127.0.0.1:${POSTGRES_SQLALCHEMY__PORT?Variable not set}:${POSTGRES_SQLALCHEMY__PORT?Variable not set}"
volumes:
  app-db-data:
  pgadmin-data:
